// <auto-generated />
using System;
using GlobalMotors.OrdersService.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GlobalMotors.OrdersService.Migrations
{
    [DbContext(typeof(GlobalMotorsOrdersContext))]
    partial class GlobalMotorsOrdersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GlobalMotors.OrdersService.Models.CartItem", b =>
                {
                    b.Property<Guid>("User")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Car")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("User", "Car");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("GlobalMotors.OrdersService.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Buyer")
                        .HasColumnType("uuid");

                    b.Property<bool?>("Delivered")
                        .HasColumnType("boolean");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GlobalMotors.OrdersService.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Order")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Car")
                        .HasColumnType("uuid");

                    b.HasKey("Order", "Car");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("GlobalMotors.OrdersService.Models.Shipping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DeliveredAt")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EstimatedDelivery")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Order")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShippingAddress")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ShippingPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Tracking")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Shippings");
                });
#pragma warning restore 612, 618
        }
    }
}
