// <auto-generated />
using System;
using GlobalMotors.OrdersService.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GlobalMotors.OrdersService.Migrations
{
    [DbContext(typeof(GlobalMotorsOrdersContext))]
    partial class GlobalMotorsOrdersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GlobalMotors.OrdersService.Models.CartItem", b =>
                {
                    b.Property<Guid>("User")
                        .HasColumnType("uuid")
                        .HasColumnName("user");

                    b.Property<Guid>("Car")
                        .HasColumnType("uuid")
                        .HasColumnName("car");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.HasKey("User", "Car")
                        .HasName("pk_cart_items");

                    b.ToTable("cart_items", (string)null);
                });

            modelBuilder.Entity("GlobalMotors.OrdersService.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("Buyer")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer");

                    b.Property<bool?>("Delivered")
                        .HasColumnType("boolean")
                        .HasColumnName("delivered");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("final_price");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer")
                        .HasColumnName("payment_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("GlobalMotors.OrdersService.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Order")
                        .HasColumnType("uuid")
                        .HasColumnName("order");

                    b.Property<Guid>("Car")
                        .HasColumnType("uuid")
                        .HasColumnName("car");

                    b.HasKey("Order", "Car")
                        .HasName("pk_order_items");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("GlobalMotors.OrdersService.Models.Shipping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("DeliveredAt")
                        .HasColumnType("date")
                        .HasColumnName("delivered_at");

                    b.Property<DateOnly>("EstimatedDelivery")
                        .HasColumnType("date")
                        .HasColumnName("estimated_delivery");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<Guid>("Order")
                        .HasColumnType("uuid")
                        .HasColumnName("order");

                    b.Property<Guid>("ShippingAddress")
                        .HasColumnType("uuid")
                        .HasColumnName("shipping_address");

                    b.Property<decimal>("ShippingPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("shipping_price");

                    b.Property<string>("Tracking")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tracking");

                    b.HasKey("Id")
                        .HasName("pk_shippings");

                    b.ToTable("shippings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
