// <auto-generated />
using System;
using GlobalMotors.UsersService.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GlobalMotors.UsersService.Migrations
{
    [DbContext(typeof(GlobalMotorsUsersContext))]
    partial class GlobalMotorsUsersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GlobalMotors.UsersService.Models.FavoriteCar", b =>
                {
                    b.Property<Guid>("User")
                        .HasColumnType("uuid")
                        .HasColumnName("user");

                    b.Property<Guid>("Car")
                        .HasColumnType("uuid")
                        .HasColumnName("car");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.HasKey("User", "Car")
                        .HasName("pk_favorite_cars");

                    b.ToTable("favorite_cars", (string)null);
                });

            modelBuilder.Entity("GlobalMotors.UsersService.Models.SystemInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_system_info");

                    b.ToTable("system_info", (string)null);
                });

            modelBuilder.Entity("GlobalMotors.UsersService.Models.UserSetting", b =>
                {
                    b.Property<Guid>("User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user");

                    b.Property<int>("DisplayedCurrency")
                        .HasColumnType("integer")
                        .HasColumnName("displayed_currency");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.HasKey("User")
                        .HasName("pk_user_settings");

                    b.ToTable("user_settings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
