using NpgsqlTypes;
using System.Text.Json.Serialization;

namespace GlobalMotors.AuthService.Models.Enums
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum BrStates
    {
        [PgName("AC")]
        AC,
        [PgName("AL")]
        AL,
        [PgName("AM")]
        AM,
        [PgName("AP")]
        AP,
        [PgName("BA")]
        BA,
        [PgName("CE")]
        CE,
        [PgName("DF")]
        DF,
        [PgName("ES")]
        ES,
        [PgName("GO")]
        GO,
        [PgName("MA")]
        MA,
        [PgName("MG")]
        MG,
        [PgName("MS")]
        MS,
        [PgName("MT")]
        MT,
        [PgName("PA")]
        PA,
        [PgName("PB")]
        PB,
        [PgName("PE")]
        PE,
        [PgName("PI")]
        PI,
        [PgName("PR")]
        PR,
        [PgName("RJ")]
        RJ,
        [PgName("RN")]
        RN,
        [PgName("RO")]
        RO,
        [PgName("RR")]
        RR,
        [PgName("RS")]
        RS,
        [PgName("SC")]
        SC,
        [PgName("SE")]
        SE,
        [PgName("SP")]
        SP,
        [PgName("TO")]
        TO
    }
}
