CREATE TYPE "payment_types" AS ENUM (
  'Transferência Bancária',
  'Débito',
  'Pix',
  'Boleto'
);

CREATE TYPE "currencies" AS ENUM (
  'USD',
  'EUR',
  'BRL'
);

CREATE TYPE "car_types" AS ENUM (
  'Novo',
  'Clássico'
);

CREATE TYPE "traction_types" AS ENUM (
  'Traseira',
  'Dianteira',
  '4x4'
);

CREATE TYPE "car_categories" AS ENUM (
  'Esportivo',
  'SUV',
  'Clássico',
  'Pick-up',
  'Elétrico'
);

CREATE TYPE "languages" AS ENUM (
  'PT-BR',
  'EN-US',
  'IT-IT'
);

CREATE TYPE "colors" AS ENUM (
  'Red',
  'White',
  'Black',
  'Blue',
  'Green'
);

CREATE TYPE "transaction_status" AS ENUM (
  'Aguardando pagamento',
  'Problema no pagamento',
  'Pagamento confirmado',
  'Carro em preparação',
  'Carro a caminho',
  'Entregue',
  'Falha na entrega'
);

CREATE TYPE "document_types" AS ENUM (
  'Física',
  'Jurídica'
);

CREATE TYPE "user_roles" AS ENUM (
  'Admin',
  'Normal',
  'Owner'
);

CREATE TYPE "genders" AS ENUM (
  'Masculino',
  'Feminino',
  'Não Informar'
);

CREATE TYPE "car_configs" AS ENUM (
  'Coupé',
  'Sedan',
  'Hatchback'
);

CREATE TYPE "shift_types" AS ENUM (
  'Automático',
  'Manual',
  'Semi-Automático'
);

CREATE TYPE "propulsion_types" AS ENUM (
  'Gasolina',
  'Diesel',
  'Híbrida',
  'Elétrico'
);

CREATE TYPE "countries" AS ENUM (
  'BR',
  'IT',
  'US',
  'DE',
  'FR'
);

CREATE TYPE "br_states" AS ENUM (
  'AC',
  'AL',
  'AM',
  'AP',
  'BA',
  'CE',
  'DF',
  'ES',
  'GO',
  'MA',
  'MG',
  'MS',
  'MT',
  'PA',
  'PB',
  'PE',
  'PI',
  'PR',
  'RJ',
  'RN',
  'RO',
  'RR',
  'RS',
  'SC',
  'SE',
  'SP',
  'TO'
);

CREATE TABLE "cars" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "price" decimal(12,2) NOT NULL,
  "currency" currencies NOT NULL,
  "model" varchar(255) NOT NULL,
  "year" int NOT NULL,
  "car_type" car_types NOT NULL,
  "mileage" decimal(8,2),
  "brand" uuid NOT NULL,
  "store" uuid NOT NULL,
  "worldwide_quantity" int,
  "national_quantity" int,
  "color" colors NOT NULL,
  "horse_power" int NOT NULL,
  "category" car_categories NOT NULL,
  "doors" int NOT NULL,
  "traction" traction_types NOT NULL,
  "car_configuration" car_configs NOT NULL,
  "shift" shift_types NOT NULL,
  "acceleration_to_hundred" decimal(10,2),
  "torque" varchar(100),
  "motorization" varchar(100),
  "propulsion" propulsion_types NOT NULL,
  "is_available" boolean DEFAULT true,
  "default_picture" varchar(255),
  "last_updated" timestamp DEFAULT (now())
);

CREATE TABLE "brands" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "name" varchar(100) NOT NULL,
  "description" varchar(255),
  "country_origin" countries NOT NULL,
  "logo" varchar(255),
  "last_updated" timestamp DEFAULT (now())
);

CREATE TABLE "stores" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "name" varchar(255) NOT NULL,
  "address" uuid,
  "cnpj" varchar(14) UNIQUE NOT NULL,
  "email" varchar(150) NOT NULL,
  "phone_number" varchar(11),
  "website" varchar(255),
  "description" varchar(255),
  "owner" uuid NOT NULL,
  "is_active" boolean NOT NULL,
  "last_updated" timestamp DEFAULT (now())
);

CREATE TABLE "addresses" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "street" varchar(150) NOT NULL,
  "number" int NOT NULL,
  "neighborhood" varchar(100) NOT NULL,
  "city" varchar(100) NOT NULL,
  "state" br_states NOT NULL,
  "postal_code" varchar(9) NOT NULL,
  "complement" varchar(150),
  "reference_point" varchar(100)
);

CREATE TABLE "shippings" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "shipping_price" decimal(10,2) NOT NULL,
  "shipping_address" uuid NOT NULL,
  "order" uuid NOT NULL,
  "tracking" varchar(40) NOT NULL,
  "estimated_delivery" date NOT NULL,
  "delivered_at" date,
  "last_updated" timestamp DEFAULT (now())
);

CREATE TABLE "favorite_cars" (
  "user" uuid,
  "car" uuid,
  "last_updated" timestamp DEFAULT (now()),
  PRIMARY KEY ("user", "car")
);

CREATE TABLE "car_images" (
  "car" uuid,
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "image" varchar(255) NOT NULL,
  PRIMARY KEY ("car", "id")
);

CREATE TABLE "cart_items" (
  "user" uuid,
  "car" uuid,
  "last_updated" timestamp DEFAULT (now()),
  PRIMARY KEY ("user", "car")
);

CREATE TABLE "orders" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "order_number" varchar(20) UNIQUE NOT NULL,
  "final_price" decimal(12,2) NOT NULL,
  "buyer" uuid NOT NULL,
  "status" transaction_status NOT NULL,
  "delivered" boolean,
  "payment_type" payment_types NOT NULL,
  "last_updated" timestamp DEFAULT (now())
);

CREATE TABLE "order_items" (
  "order" uuid,
  "car" uuid,
  PRIMARY KEY ("order", "car")
);

CREATE TABLE "users" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "email" varchar(150) NOT NULL,
  "password" varchar(100) NOT NULL,
  "role" user_roles NOT NULL,
  "phone_number" varchar(11),
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "birthday" date NOT NULL,
  "document_number" varchar(14) UNIQUE NOT NULL,
  "document_type" document_types NOT NULL,
  "gender" genders NOT NULL,
  "picture" varchar(255),
  "current_address" uuid,
  "last_updated" timestamp DEFAULT (now())
);

CREATE TABLE "user_settings" (
  "user" uuid PRIMARY KEY,
  "language" languages DEFAULT 'PT-BR',
  "displayed_currency" currencies DEFAULT 'USD',
  "last_updated" timestamp DEFAULT (now())
);

CREATE TABLE "archived_cars" (
  "id" uuid PRIMARY KEY,
  "price" decimal(12,2) NOT NULL,
  "currency" currencies NOT NULL,
  "model" varchar(255) NOT NULL,
  "year" int NOT NULL,
  "car_type" car_types NOT NULL,
  "mileage" decimal(8,2),
  "brand" uuid NOT NULL,
  "store" uuid NOT NULL,
  "worldwide_quantity" int,
  "national_quantity" int,
  "color" colors NOT NULL,
  "horse_power" int NOT NULL,
  "category" car_categories NOT NULL,
  "doors" int NOT NULL,
  "traction" traction_types NOT NULL,
  "car_configuration" car_configs NOT NULL,
  "shift" shift_types NOT NULL,
  "acceleration_to_hundred" decimal(10,2),
  "torque" varchar(100),
  "motorization" varchar(100),
  "propulsion" propulsion_types NOT NULL,
  "is_available" boolean,
  "default_picture" varchar(255),
  "last_updated" timestamp
);

CREATE TABLE "archived_brands" (
  "id" uuid PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" varchar(255),
  "country_origin" countries NOT NULL,
  "logo" varchar(255),
  "last_updated" timestamp
);

CREATE TABLE "archived_stores" (
  "id" uuid PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "address" uuid,
  "cnpj" varchar(14) UNIQUE NOT NULL,
  "email" varchar(150) NOT NULL,
  "phone_number" varchar(11),
  "website" varchar(255),
  "description" varchar(255),
  "owner" uuid NOT NULL,
  "is_active" boolean NOT NULL,
  "last_updated" timestamp
);

CREATE TABLE "archived_addresses" (
  "id" uuid PRIMARY KEY,
  "street" varchar(150) NOT NULL,
  "number" int NOT NULL,
  "neighborhood" varchar(100) NOT NULL,
  "city" varchar(100) NOT NULL,
  "state" br_states NOT NULL,
  "postal_code" varchar(9) NOT NULL,
  "complement" varchar(150),
  "reference_point" varchar(100)
);

CREATE TABLE "system_info" (
  "id" integer PRIMARY KEY DEFAULT 1,
  "version" varchar
);

CREATE TABLE "conversion_rate" (
  "currency" currencies PRIMARY KEY,
  "rate" decimal(5,2),
  "last_updated" timestamp
);

ALTER TABLE "cars" ADD FOREIGN KEY ("brand") REFERENCES "brands" ("id");

ALTER TABLE "cars" ADD FOREIGN KEY ("store") REFERENCES "stores" ("id");

ALTER TABLE "stores" ADD FOREIGN KEY ("address") REFERENCES "addresses" ("id");

ALTER TABLE "stores" ADD FOREIGN KEY ("owner") REFERENCES "users" ("id");

ALTER TABLE "shipping" ADD FOREIGN KEY ("shipping_address") REFERENCES "archived_addresses" ("id");

ALTER TABLE "shipping" ADD FOREIGN KEY ("order") REFERENCES "orders" ("id");

ALTER TABLE "favorite_cars" ADD FOREIGN KEY ("user") REFERENCES "users" ("id");

ALTER TABLE "favorite_cars" ADD FOREIGN KEY ("car") REFERENCES "cars" ("id");

ALTER TABLE "car_images" ADD FOREIGN KEY ("car") REFERENCES "cars" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("user") REFERENCES "users" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("car") REFERENCES "cars" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("buyer") REFERENCES "users" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order") REFERENCES "orders" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("car") REFERENCES "archived_cars" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("current_address") REFERENCES "addresses" ("id");

ALTER TABLE "user_settings" ADD FOREIGN KEY ("user") REFERENCES "users" ("id");

ALTER TABLE "archived_cars" ADD FOREIGN KEY ("brand") REFERENCES "archived_brands" ("id");

ALTER TABLE "archived_cars" ADD FOREIGN KEY ("store") REFERENCES "archived_stores" ("id");

ALTER TABLE "archived_stores" ADD FOREIGN KEY ("address") REFERENCES "archived_addresses" ("id");

ALTER TABLE "archived_stores" ADD FOREIGN KEY ("owner") REFERENCES "users" ("id");
